version: '3.2'
services: 
    api:
        build: . # Dockerfile
        container_name: happy_api
        depends_on:
            - db
            - redis
        environment: 
            DB_HOST: postgres_db
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            REDIS_HOST: redis_db
            REDIS_PORT: ${REDIS_PORT}
            REDIS_PASS: ${REDIS_PASS}
        ports: 
            - "3000:3000"
    db: 
        image: postgres:latest
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        expose:
            - ${DB_PORT} # Only to container
        restart: always
    redis:
        image: redis:alpine
        container_name: redis_db
        expose:
            - ${REDIS_PORT}
        command: redis-server --requirepass ${REDIS_PASS}